# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PythonTrier
email: pythontrier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Helping grow the community of Python developers by sharing what we know with those that come to learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pythontrier.github.io" # the base hostname & protocol for your site

google_analytics: UA-89152428-1

# Build settings
markdown: kramdown

exclude: [
  "bower.json",
  "bower_components",
  "Gemfile",
  "node_modules",
  "output",
  "package.json",
  "README.md",
  "webpack.config.js",
  "webpack.production.config.js",
  "*.iml"
]
